# ?????
server:
  port: 80

spring:
  main:
    banner-mode: 'off' # ?????System.out??banner
  datasource: # ?????
    druid:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3306/website #?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
      username: root
      password: 995716

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    # MP??
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl